bmi_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.get_bmi, name='get_bmi'),
    path('add_bmi/', views.bmi_add_view, name='add_bmi'),
    path('update_bmi/<int:pk>', views.bmi_update_view, name='update_bmi'),
]

calorie_counter/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('users.urls')),
    path('',include('fit.urls')),
    path('BMI/',include('bmi_app.urls')),
]

fit/urls.py
from django.urls import path
from .views import (
    homeView,
    userPageView,
    createFoodItemView,
    foodItemView,
    addFoodItemView,
    setCalories,
    updateCalories
)

urlpatterns = [
    path('',userPageView,name='user_page'),
    path('fit/admin/',homeView,name='home'),
    path('create_food_item/',createFoodItemView,name='createFoodItem'),
    path('product/',foodItemView,name='foodItem'),
    path('add_food_item/',addFoodItemView,name='addFoodItem'),
    path('set_calories/',setCalories,name='setCalories'),
    path('update_calories/',updateCalories,name='update_Calories'),
]

bmi_app/models.py
from django.db import models
from users.models import user
# Create your models here.
class BMI(models.Model):
    gender = (
        ('male','male'),
        ('female','female'),
    )
    activity = (
        ('Sedentary','sedentary'),
        ('Little/No exercise','Little/No exercise'),
        ('Low activity (exercise 1-3 times/week)','Low activity (exercise 1-3 times/week)'),
        ('Active (daily exercise or intense exercise 3-4 times/week)','Active (daily exercise or intense exercise 3-4 times/week)'),
        ('High activity (intense exercise 6-7 times/week)','High activity (intense exercise 6-7 times/week)'),
        ('Very high activity (very intense exercise daily, or physical job)','Very high activity (very intense exercise daily, or physical job)'),
    )
    user = models.OneToOneField(user, on_delete=models.CASCADE)
    gender = models.CharField(max_length=100, choices=gender,null=True)
    height = models.IntegerField(blank=True)
    weight = models.IntegerField(blank=True)
    rate_of_activity=models.CharField(max_length=100,choices=activity,null=True)
    bmi = models.DecimalField(decimal_places=3,max_digits=1000,blank=True)

bmi_app/forms.py
from django import forms
from .models import BMI

class BMIForm(forms.ModelForm):
    class Meta:
        model = BMI
        fields = ['gender','height','weight','rate_of_activity']
        labels = ['Gender','Height','Weight','Rate of activity']
        widgets = {
            'gender': forms.RadioSelect,
            'height': forms.NumberInput(attrs={'placeholder':'cm'}),
            'weight': forms.NumberInput(attrs={'placeholder':'kg'}),
            'rate_of_activity': forms.RadioSelect,
        }

bmi_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import BMI
from .forms import BMIForm
# Create your views here.
def bmi_add_view(request):
    if request.method == 'POST':
        form = BMIForm(request.POST)
        if form.is_valid():
            user = request.user
            gender = form.cleaned_data['gender']
            height = form.cleaned_data['height']
            n_height = height/100
            weight = form.cleaned_data['weight']
            rate_of_activity = form.cleaned_data['rate_of_activity']
            bmi = weight/(n_height**2)
            BMI.objects.create(
                user=user,
                gender=gender,
                height=height,
                weight=weight,
                rate_of_activity=rate_of_activity,
                bmi=bmi
            )
            return redirect('get_bmi')
    else:
        form = BMIForm()
    return render(request, 'bmi/bmi_add.html', {'form': form})

def get_bmi(request):
    user = request.user
    try:
        bmi = BMI.objects.get(user=user)
        form = BMIForm(instance=user)
    except BMI.DoesNotExist:
        return redirect('add_bmi')
    return render(request, 'bmi/bmi_calculator.html', {'form': form,'bmi':bmi})

def bmi_update_view(request, pk):
    bmi = get_object_or_404(BMI, pk=pk)
    
    if request.method == 'POST':
        form = BMIForm(request.POST, instance=bmi)
        if form.is_valid():
            user = request.user
            gender = form.cleaned_data['gender']
            height = form.cleaned_data['height']
            n_height = height/100
            weight = form.cleaned_data['weight']
            rate_of_activity = form.cleaned_data['rate_of_activity']
            bmi = weight/(n_height**2)
            BMI.objects.update(
                user=user,
                gender=gender,
                height=height,
                weight=weight,
                rate_of_activity=rate_of_activity,
                bmi=bmi
            )
            return redirect('get_bmi')
    else:
        form = BMIForm(instance=bmi)
    
    return render(request, 'bmi/bmi_update.html', {'form': form})

bmi_app/templates/bmi/bmi_add.html
{% extends 'fit/base.html' %}
{% block title %}BMI Calculator{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
<form action="" method="POST">
    <legend>Add BMI info</legend>
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success" type="submit">Submit</button>
</form>
{% endblock content %}

bmi_app/templates/bmi/bmi_calculator.html
{% extends 'fit/base.html' %}
{% block title %}BMI Calculator{% endblock title %}
{% block content %}

{% load crispy_forms_tags %}
{% if user.is_authenticated %}
<div class="d-flex">
    <div class="container">
    <h1>Your BMI Details:</h1>
    <p> <strong>Gender:</strong> {{ bmi.get_gender_display }}</p>
    <p> <strong>Height:</strong> {{ bmi.height }} cm</p>
    <p> <strong>Weight:</strong> {{ bmi.weight }} kg</p>
    <p> <strong>Rate of Activity:</strong> {{ bmi.get_rate_of_activity_display }}</p>
    <p> <strong>BMI:</strong> {{ bmi.bmi }}</p>
    <br>
    </div> 
    <div class="ms-auto justify-content-end">
      <a href="{% url 'update_bmi' bmi.id %}" class="btn btn-info text-light" style="font-size: 25px;">Update BMI</a>
    </div>
   </div> 
    
  
  {% endif %}
{% endblock content %}

bmi_app/templates/bmi/bmi_update.html
{% extends 'fit/base.html' %}
{% block title %}BMI Calculator{% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
<form action="" method="POST">
    <legend>Update BMI info</legend>
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success" type="submit">Submit</button>
</form>
{% endblock content %}